"""Default component sets for various multiblocks."""

from .turbine import OVERHAULED_TURBINE_DYNAMO_COMPONENTS, OVERHAULED_TURBINE_ROTOR_COMPONENTS, OVERHAULED_TURBINE_ROTOR_COMPONENTS_QMD
from .accelerator import QMD_ACCELERATOR_COMPONENTS, QMD_LINEAR_ACCELERATOR_COMPONENTS
from .nucleosynthesis import QMD_NUCLEOSYNTHESIS_COMPONENTS
